# fly.toml app configuration file generated for sensor-backend on 2025-04-20T12:23:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sensor-backend'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
